### ISSUE TITLE
Bug - No check if the file exists before using it

### ISSUE THREAD

**Issue by falkos** [znuny/ZnunyCodePolicy#2]
### Environment

- OS:           Linux
- Browser:   Safari
- OTRS version: 6.0.24

### Expected behavior

I would have expected an error message that there is the SOPM missing. 

### Actual behavior

I see a Perl exception / error that the value is not def. 

### How to reproduce

I've testet the Tool and in case there is no RELEASE File in the Root-Path and no SOPM File i will get a error msg. 

Can't call method "getlines" on an undefined value at /opt/ZnunyCodePolicy/Kernel/TidyAll/Znuny.pm line 99.

### Additional information

it would be nice to have an option that the sopm is in a sub-folder.

**Comment by dennykorsukewitz** [comment]
Hi @falkos,

you are right! :rocket:

The repo `ZnunyCodePolicy` was created from the repo `otrscodepolicy` and partly from our CodePolicy for packages.

This repo is only to test the framework itself.
There should never be a SOPM here. 
We will discuss the future behavior, whether it should also be functional for znuny packages.

Thanks for your report.

https://github.com/znuny/ZnunyCodePolicy/blob/master/Kernel/TidyAll/Znuny.pm#L71

```perl
sub DetermineFrameworkVersionFromDirectory {
    my ( $Self, %Param ) = @_;

    # First check if we have an OTRS directory, use RELEASE info then.
    if ( -r $Self->{root_dir} . '/RELEASE' ) {
        my $FileHandle = IO::File->new( $Self->{root_dir} . '/RELEASE', 'r' );
        my @Content    = $FileHandle->getlines();

        my ( $VersionMajor, $VersionMinor ) = $Content[1] =~ m{^VERSION\s+=\s+(\d+)\.(\d+)\.}xms;
        $FrameworkVersionMajor = $VersionMajor;
        $FrameworkVersionMinor = $VersionMinor;

# ---
        # ZnunyCodePolicy
# ---
        if ( $Content[0] =~ m{\APRODUCT\s*=\s*(.*)} ) {
            $ProductName = $1;
        }

# ---
    }
    else {
        # Now check if we have a module directory with an SOPM file in it.
        my @SOPMFiles = glob $Self->{root_dir} . "/*.sopm";
        if (@SOPMFiles) {

            # Use the highest framework version from the first SOPM file.
            my $FileHandle = IO::File->new( $SOPMFiles[0], 'r' );
            my @Content    = $FileHandle->getlines();```

**Comment by dennykorsukewitz** [comment]
Fixed via https://github.com/znuny/ZnunyCodePolicy/commit/611e36bd78899e0f749234630c2337efb2f4a003
Added additional file check before using $FileHandle->getlines() on sopm.
